/**
 * 可观测（46–50）：结构化日志（见 logger.ts）、OpenAPI 生成、Swagger UI / ReDoc、Prometheus 指标。
 */

import type { Context } from './context';
import type { OASchema } from './validators';

// ==========================================================================
// Prometheus 指标（请求数 / 延迟 / P99）
// ==========================================================================
export interface MetricStore {
  httpRequestsTotal: Map<string, number>;           // key: method+route+status
  httpRequestDurationMs: Map<string, number[]>;      // key: route -> 采样数组
}

export function createMetrics(): MetricStore {
  return { httpRequestsTotal: new Map(), httpRequestDurationMs: new Map() };
}

function quantile(arr: number[], q: number): number {
  if (arr.length === 0) return 0;
  const s = [...arr].sort((a, b) => a - b);
  const pos = (s.length - 1) * q;
  const base = Math.floor(pos);
  const rest = pos - base;
  if (s[base + 1] !== undefined) return s[base] + rest * (s[base + 1] - s[base]);
  return s[base];
}

/** 序列化 Prometheus 文本格式 */
export function renderPrometheus(metrics: MetricStore): string {
  const lines: string[] = [];
  const sorted = Array.from(metrics.httpRequestsTotal.entries()).sort((a, b) => (a[0] < b[0] ? -1 : 1));
  for (const [key, val] of sorted) {
    const parts = key.split('|');
    const [method, route, status] = parts;
    lines.push(
      `http_requests_total{method="${method}",route="${route}",status="${status}"} ${val}`
    );
  }
  // 延迟 summary
  for (const [route, arr] of metrics.httpRequestDurationMs.entries()) {
    lines.push(`http_request_duration_seconds{quantile="0.5",route="${route}"} ${quantile(arr, 0.5) / 1000}`);
    lines.push(`http_request_duration_seconds{quantile="0.95",route="${route}"} ${quantile(arr, 0.95) / 1000}`);
    lines.push(`http_request_duration_seconds{quantile="0.99",route="${route}"} ${quantile(arr, 0.99) / 1000}`);
    lines.push(`http_request_duration_seconds_count{route="${route}"} ${arr.length}`);
    lines.push(`http_request_duration_seconds_sum{route="${route}"} ${arr.reduce((a, b) => a + b, 0) / 1000}`);
  }
  return lines.join('\n') + '\n';
}

// ==========================================================================
// OpenAPI 3.1 生成
// ==========================================================================
export interface OpenApiRoute {
  path: string;
  method: string;
  summary?: string;
  description?: string;
  tags?: string[];
  schema?: {
    query?: { params?: Record<string, OASchema> };
    params?: { params?: Record<string, OASchema> };
    body?: OASchema;
    response?: OASchema;
  };
}

export interface OpenApiBuilderOptions {
  defaultMethod?: string;
}

export function buildOpenApi(routes: OpenApiRoute[], opts: {
  title?: string;
  version?: string;
  description?: string;
} = {}): Record<string, unknown> {
  const paths: Record<string, any> = {};
  for (const r of routes) {
    // 转成 openapi 路径（:param 与 :param(regex) 一律归一为 {name}）
    const opath = r.path
      .replace(/:([A-Za-z0-9_]+)\((?:\\.|[^)])*\)/g, '{$1}')
      .replace(/:([A-Za-z0-9_]+)/g, '{$1}');
    if (!paths[opath]) paths[opath] = {};
    const m = r.method.toLowerCase();
    const op: Record<string, any> = {};
    if (r.summary) op.summary = r.summary;
    if (r.description) op.description = r.description;
    op.tags = r.tags ?? [];
    const params: any[] = [];

    // path params
    if (r.schema?.params?.params) {
      for (const [name, s] of Object.entries(r.schema.params.params)) {
        params.push({ name, in: 'path', required: true, schema: s });
      }
    }
    // query params
    if (r.schema?.query?.params) {
      for (const [name, s] of Object.entries(r.schema.query.params)) {
        params.push({ name, in: 'query', required: !s.nullable, schema: s });
      }
    }
    if (params.length) op.parameters = params;

    // request body
    if (r.schema?.body) {
      op.requestBody = {
        required: true,
        content: {
          'application/json': { schema: r.schema.body },
        },
      };
    }
    // response
    op.responses = {
      '200': {
        description: 'Successful response',
        content: r.schema?.response
          ? { 'application/json': { schema: r.schema.response } }
          : undefined,
      },
      '422': { description: 'Validation error' },
      '404': { description: 'Not found' },
    };
    // 清理空 content
    if (op.responses['200'].content === undefined) delete op.responses['200'].content;

    paths[opath][m] = op;
  }
  return {
    openapi: '3.1.0',
    info: {
      title: opts.title ?? 'request-neo API',
      version: opts.version ?? '1.0.0',
      description: opts.description ?? 'Generated by request-neo',
    },
    paths,
  };
}

// ==========================================================================
// Swagger UI 静态页
// ==========================================================================
export function swaggerUiHtml(openapiPath: string, title = 'API Docs'): string {
  return `<!DOCTYPE html>
<html lang="zh">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <title>${title}</title>
  <link rel="stylesheet" href="https://unpkg.com/swagger-ui-dist@5/swagger-ui.css"/>
</head>
<body>
  <div id="swagger-ui"></div>
  <script src="https://unpkg.com/swagger-ui-dist@5/swagger-ui-bundle.js"></script>
  <script>
    window.onload = function () {
      window.ui = SwaggerUIBundle({
        url: ${JSON.stringify(openapiPath)},
        dom_id: '#swagger-ui',
        deepLinking: true,
        presets: [
          SwaggerUIBundle.presets.apis,
          SwaggerUIBundle.SwaggerUIStandalonePreset
        ]
      });
    };
  </script>
</body>
</html>`;
}

export function reDocHtml(openapiPath: string, title = 'API Reference'): string {
  return `<!DOCTYPE html>
<html lang="zh">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <title>${title}</title>
  <style>body{margin:0;padding:0}</style>
</head>
<body>
  <redoc spec-url=${JSON.stringify(openapiPath)}></redoc>
  <script src="https://unpkg.com/redoc@2.0.0/bundles/redoc.standalone.js"></script>
</body>
</html>`;
}

// 供 app.ts 使用的 Observer 结构
export interface ObserverImpl {
  recordRequest(method: string, route: string, status: number, ms: number): void;
}